### ISSUE TITLE
Connectionstring missing not resulting in config view

### ISSUE THREAD

**Issue by renemadsen** [microting/eform-angular-frontend#146]
**The steps to reproduce the bug**
Get the clean .net core edition.
Start the API part and run the node part.
Open chrome at localhost:4200
The result is 404 errors and a "connection string does not exist" error, but no redirect to config view.

**The expected behavior of the application**
When there is no connection string, redirect to the config view.

**The observed behavior of the application**
The page just gives 404 errors and the error message "connection string does not exist" and stays on the same page.

**Information about your environment/platform**
The problems is found on version 2.0.319 in .net core

**Comment by renemadsen** [comment]
Problem does not exist if you reproduce in inkognito.

**Comment by Gid733** [comment]
Fixed in #153
