### ISSUE TITLE
Security group edit permission (menu)

### ISSUE THREAD

**Issue by renemadsen** [microting/eform-angular-frontend#150]
•	Implement HTML with panels and tabs to display CRUD security for each category (all advanced menu, eforms, users)
•	Add services to read and update permissions on angular part
•	Implement API to get/update required menu entires
•	Rework API requests for all CRUD actions in required menu entries
•	Rework how we obtain menu on the angular part, add services and corresponsive requests
•	Create API part to handle menu from plugins and main functionality
•	Implement DB architecture to store and write menu to the database

**Comment by Gid733** [comment]
Added in #157
