### ISSUE TITLE
Security group edit permission (eforms)

### ISSUE THREAD

**Issue by renemadsen** [microting/eform-angular-frontend#151]
•	Create HTML with buttons to allow or deny all actions for eform. Implement angular services to handle functionality for each eform in particular group
•	Create modal window to add eforms to groups
•	Implement DB architecture to store permission for eform and eform actions. By default, all eforms are not available for anyone
•	Add API to work with permissions for each eform
•	Rework eform methods to handle permissions part

**Comment by Gid733** [comment]
Added in #157
