### ISSUE TITLE
Clicking cancel in save changes dialog breaks site

### ISSUE THREAD

**Issue by renemadsen** [microting/eform-angular-frontend#159]
**The steps to reproduce the bug**
Edit a case for any eForm.
Try to navigate away.
Click cancel in the dialog

**The expected behavior of the application**
Clicking on any navigational link, should still work.

**The observed behavior of the application**
Alle navigation is now broken. Even after clicking Save on the given case.

**Information about your environment/platform**
Found in .Net v2.0.352.0
Not tested in .Net Core
Tested on:
- OSX
- Windows
- Ubuntu

**Comment by Gid733** [comment]
Fixed in #162 for .NET 4.6
