### ISSUE TITLE
Deleting case does not remove it from view

### ISSUE THREAD

**Issue by renemadsen** [microting/eform-angular-frontend#160]
**The steps to reproduce the bug**
Go to lists of cases for any eForm.
Delete a case.

**The expected behavior of the application**
It's expected that the case in question is removed from the list.

**The observed behavior of the application**
The case is not removed from the list.
Pressing F5 will load the list without the case in it.

**Information about your environment/platform**
Found in .Net v2.0.352.0
Not tested in .Net Core
Tested on:

- OSX
- Windows
- Ubuntu

**Comment by Gid733** [comment]
Fixed in #162 for .NET 4.6
