### ISSUE TITLE
Missing translations Danish/English

### ISSUE THREAD

**Issue by renemadsen** [microting/eform-angular-frontend#161]
We need to get rid of missing translations like:

![bugs angular 121018-3](https://user-images.githubusercontent.com/76994/48249017-e00b5100-e3f9-11e8-8998-40d9492c1b0d.png)

The user is logged in with Danish, but some parts of the dialog is in Eniglish.

**Comment by Gid733** [comment]
Fixed in #174 for .NET Core

**Comment by Gid733** [comment]
Fixed in #175 for legacy .NET
