### ISSUE TITLE
Keep sorting of tables even after refresh

### ISSUE THREAD

**Issue by renemadsen** [microting/eform-angular-frontend#167]
In order for us to give the user a good experience we need to keep the sorting even after the user have done a refresh of the view.
![bugs angular - sort display order should stay the same](https://user-images.githubusercontent.com/76994/48554733-7e5a5380-e8df-11e8-9131-a6bd774ccfc2.png)

**Comment by Gid733** [comment]
Added in #181 for .NET Core

**Comment by Gid733** [comment]
Added in #183 for legacy .NET
