### ISSUE TITLE
Version number as part of footer

### ISSUE THREAD

**Issue by renemadsen** [microting/eform-angular-frontend#169]
For making it faster to support end users, we need to have the current version number in the footer.

Both in master and netcore branch.

**Comment by Gid733** [comment]
Added in #175 for legacy .NET

**Comment by Gid733** [comment]
Added in #176 for .NET Core

**Comment by Gid733** [comment]
Updated in #179 for .NET core

**Comment by Gid733** [comment]
Update for legacy .NET in #180
